name: Publish

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - .github/workflows/*
      - .gitignore
      - idea/*
      - Readme.md
jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Flow.Launcher.Plugin.KomorebiWorkspaceNamer\plugin.json'
          prop_path: 'Version'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        shell: pwsh
        run: |
          dotnet publish 'Flow.Launcher.Plugin.KomorebiWorkspaceNamer\Flow.Launcher.Plugin.KomorebiWorkspaceNamer.csproj' -c Release -o "KomorebiWorkspaceNamer"
          Compress-Archive -Path KomorebiWorkspaceNamer/* -DestinationPath Flow.Launcher.Plugin.KomorebiWorkspaceNamer.zip -Force

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Flow.Launcher.Plugin.KomorebiWorkspaceNamer.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}